spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: hxweaving.com:8849
    gateway:
      routes:
        - id: consumer-service # 路由标示，必须唯一
          uri: lb://consumer-service # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/consumer/** # 路径断言，判断路径是否是以/consumer开头，如果是则符合
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**  # should be the same as the service context-path
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**  # should be the same as the service context-path
server:
  port: 53010